# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.disksize.size = '20GB'
  config.vm.synced_folder "../ansible02", "/home/vagrant/ansible02", create: true
  config.vm.synced_folder "../consul01", "/home/vagrant/consul01", create: true
  config.vm.synced_folder "../services", "/home/vagrant/services", create: true


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
  
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.provision "ansible-setup", type: "shell", path: "../script/setup.sh"
    manager.vm.provision "ssh-setup", type: "shell", path: "../script/key+1.sh", run: "never"
  end
  
  config.vm.define "ConsulServer" do |cserver|
    cserver.vm.hostname = "consulserver"
    cserver.vm.network "private_network", ip: "192.168.56.11"
    cserver.vm.network  "forwarded_port", guest: 8500, host: 8500
  end

  config.vm.define "api" do |api|
    api.vm.hostname = "api"
    api.vm.network "private_network", ip: "192.168.56.12"
    api.vm.network  "forwarded_port", guest: 8082, host: 8082
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.13"
  end

end
