# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.disksize.size = '20GB'
  config.vm.synced_folder "./services", "/home/vagrant/services", create: true
  config.vm.synced_folder "./ansible01", "/home/vagrant/ansible01", create: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end
  
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.provision "ansible-setup", type: "shell", path: "./script/setup.sh"
    manager.vm.provision "ssh-setup", type: "shell", path: "./script/key.sh", run: "never"
  end
  
  config.vm.define "node01" do |node|
    node.vm.hostname = "node01"
    node.vm.network "private_network", ip: "192.168.56.11"
    node.vm.network  "forwarded_port", guest: 8081, host: 8081
    node.vm.network  "forwarded_port", guest: 8087, host: 8087
  end

    config.vm.define "node02" do |node|
    node.vm.hostname = "node02"
    node.vm.network "private_network", ip: "192.168.56.12"
  end

end
